### ISSUE TITLE
Next Steps Till Baseline Systems

### ISSUE THREAD

**Issue by mtsandra** [nabinkim0318/Customized_Playlist_Generator#1]
- [ ] Fix Spotify API input to be fed into the clustering algorithm @nabinkim0318 
- [ ] Get Essentia to work, if not, find alternative feature extractor @mtsandra 
- [ ] Match MSD artist, song details to do a YouTube search
- [x] Download audio from YouTube search
- [ ] Run feature extractors through each cluster
- [ ] Compile into playlist

### Genre Classifier
- [ ] Train genre classifier with GTZAN
- [ ] Run the playlist through genre classifier
- [ ] Concatenate result into playlist output

**Comment by nabinkim0318** [comment]
- using luhee's code to extract the features and organize it as a dataframe
- exploring h5 files so that why there are big arrays for the features --> preprocess for clustering algorithms them if needed
- -
