### ISSUE TITLE
Week 2

### ISSUE THREAD

**Issue by nabinkim0318** [nabinkim0318/Customized_Playlist_Generator#2]
@nabinkim0318 
- using luhee's code to extract the features and organize it as a dataframe
- exploring h5 files so that why there are big arrays for the features --> preprocess for clustering algorithms them if needed
-  testing clustering algorithms

**Comment by mtsandra** [comment]
- [ ] get feature extractor to run and test with two clips of audio
- Feature extractor: https://arxiv.org/pdf/1703.09179.pdf
- Github repo: https://github.com/keunwoochoi/transfer_learning_music
- [ ] (if possible) look at nabin's clustering code and see if there are ways to optimize it

**Comment by mtsandra** [comment]
transformer fine tuning for genre classifier: https://huggingface.co/learn/audio-course/chapter4/fine-tuning
